// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9rmEdZQXapztZuBL6tK5jCJ0pVbzM1RA',
    appId: '1:516224053978:web:ee91f23d78d22566e42be3',
    messagingSenderId: '516224053978',
    projectId: 'spotify-clone-01-02',
    authDomain: 'spotify-clone-01-02.firebaseapp.com',
    storageBucket: 'spotify-clone-01-02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWaeeLER6nKt2kF6sIuZgl_kr1uAUe58',
    appId: '1:516224053978:android:1277195039b0fc07e42be3',
    messagingSenderId: '516224053978',
    projectId: 'spotify-clone-01-02',
    storageBucket: 'spotify-clone-01-02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQk2avOU7fsQ87dvL8Op1DqwwodE_uU4o',
    appId: '1:516224053978:ios:f517fc962cce8738e42be3',
    messagingSenderId: '516224053978',
    projectId: 'spotify-clone-01-02',
    storageBucket: 'spotify-clone-01-02.appspot.com',
    iosBundleId: 'com.example.spotifyCloneTwo',
  );
}
